apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reviews-mock
  namespace: load
spec:
  workloadSelector:
    labels:
      app: productpage
      mock: enabled
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: ANY
        routeConfiguration:
          portNumber: 9080
          vhost:
            route:
              name: "mock"
      patch:
        operation: MERGE
        value:
          name: direct-response
          match:
            prefix: /reviews
          directResponse:
            body:
              inlineString: '{"id": "100","podname": "reviews-v1-68b4dcbdb9-xwfsh","clustername": "null","reviews": [{  "reviewer": "Reviewer1",  "text": "Mock An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!"},{  "reviewer": "Reviewer2",  "text": "Mock Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare."}]}'
            status: 200
---            
##################################################################################################
# Reviews service MOCK ROUTING
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
    - name: v1
      labels:
        version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - name: "mock"
      match:
        - sourceLabels:
            mock: enabled
      route:
        - destination:
            host: reviews
    - route:
        - destination:
            host: reviews
            subset: v1
---            
