apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: wiremock
  namespace: load
spec:
  parallelism: 1
  script:
    configMap: 
      name: wiremock
      file: k6-script.js
      mountPath: /home/k6/
  runner:
    image: ghcr.io/nsl-test/xk6:v0.6
    env:
      - name: K6_PROMETHEUS_REMOTE_URL
        value: https://prometheus-prod-10-prod-us-central-0.grafana.net/api/prom/push
      - name: K6_OUT
        value: output-prometheus-remote
      - name: K6_PROMETHEUS_USER
        value: "429236"
      - name: K6_PROMETHEUS_PASSWORD
        valueFrom:
          secretKeyRef:
            key: GRAFANA_PASSWORD
            name: grafana-password
  scuttle:
    enabled: "true"
