##################################################################################################
# Reviews service MOCK
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews-mock
  labels:
    app: reviews
    version: mock
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: mock
  template:
    metadata:
      labels:
        app: reviews
        version: mock
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: bookinfo
      containers:
        - name: reviews
          image: docker.io/rbillon59/wiremock-loadtest:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "9080"
          ports:
            - containerPort: 9080
          volumeMounts:
            - name: wiremock-mapping
              mountPath: /home/wiremock/mappings
          securityContext:
            runAsUser: 1000
      volumes:
        - name: wiremock-mapping
          configMap:
            name: wiremock-mapping
---
##################################################################################################
# Reviews service MOCK ROUTING
##################################################################################################
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: reviews
spec:
  host: reviews
  subsets:
    - name: v1
      labels:
        version: v1
    - name: mock
      labels:
        version: mock
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
    - name: mock
      match:
        - sourceLabels:
            mock: enabled
      route:
        - destination:
            host: reviews
            subset: mock
    - route:
        - destination:
            host: reviews
            subset: v1