version: '3.8'

networks:
  k6:

services:
  prometheus:
    image: prom/prometheus:latest
    command: --web.enable-remote-write-receiver --config.file=/etc/prometheus/prometheus.yml
    networks:
      - k6
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    networks:
      - k6
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./deploy/grafana/config-datasources.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./deploy/grafana/config-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./deploy/grafana/dashboards:/var/lib/grafana/dashboards
      
  k6:
    image: ghcr.io/nsl-test/xk6:v0.7
    networks:
      - k6
    ports:
      - "6565:6565"
    environment:
      - K6_PROMETHEUS_REMOTE_URL=http://192.168.28.43:9090/api/v1/write
      - K6_OUT=output-prometheus-remote
    volumes:
      - ./iam:/home/k6/
    depends_on:
      - prometheus