apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/grafana/k6-operator//config/default
  - github.com/rancher/local-path-provisioner/deploy?ref=v0.0.22
generatorOptions:
  labels:
    grafana_dashboard: "1"
  disableNameSuffixHash: true
configMapGenerator:
  - name: k6-dashboard
    files:
      - grafana/dashboards/default.json
helmCharts:
  - name: grafana
    releaseName: grafana
    repo: https://grafana.github.io/helm-charts
    includeCRDs: false
    namespace: k6-operator-system
    valuesInline:
      rbac:
        pspEnabled: false
        pspUseAppArmor: false
        namespaced: true
      testFramework:
        enabled: false
      adminPassword: "strongpassword"
      env:
        GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: false
        GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
        GF_AUTH_ANONYMOUS_ENABLED: true
        GF_AUTH_BASIC_ENABLED: false
      sidecar:
        datasources:
          enabled: true
          searchNamespace: ALL
        dashboards:
          enabled: true
          searchNamespace: ALL
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: prometheus
              type: prometheus
              url: http://prometheus-server
              access: proxy
              isDefault: true
              basicAuth: false
              jsonData:
                tlsAuth: false
                tlsAuthWithCACert: false
              editable: false
  # - name: victoria-metrics-single
  #   repo: https://victoriametrics.github.io/helm-charts/
  #   releaseName: prometheus
  #   includeCRDs: false
  #   namespace: k6-operator-system
  #   valuesInline:
  #     nameOverride: prometheus
  #     server:
  #       retentionPeriod: 2d
  #       extraArgs:
  #         maxInsertRequestSize: 10MB
  #       persistentVolume:
  #         size: 5Gi
  #         storageClass: local-path
  #       statefulSet:
    #         enabled: false
  - name: prometheus
    includeCRDs: false
    namespace: k6-operator-system
    valuesInline:
      alertmanager:
        enabled: false
      nodeExporter:
        enabled: false
      pushgateway:
        enabled: false
      server:
        extraFlags:
          - web.enable-remote-write-receiver
        persistentVolume:
          size: 2Gi
          storageClass: local-path
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus
