apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample
  namespace: k6-operator-system
spec:
  parallelism: 1
  script:
    configMap: 
      name: iam-test
      file: k6-script.js
  runner:
    image: ghcr.io/nsl-test/xk6:v0.4
    env:
      - name: K6_PROMETHEUS_REMOTE_URL
        value: http://prometheus-server/api/v1/write
  arguments: --out output-prometheus-remote