# apiVersion: networking.istio.io/v1alpha3
# kind: Sidecar
# metadata:
#   name: sleep-outbound
#   namespace: load
# spec:
#   workloadSelector:
#     labels:
#       app: sleep
#   egress:
#   - port:
#       number: 9080
#       protocol: TCP
#       name: reviews
#     captureMode: NONE
#     # bind: 127.0.0.1
#     hosts:
#     - "*/reviews.load.svc.cluster.local"
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: EnvoyFilter
# metadata:
#   name: sleep-mock
#   namespace: load
# spec:
#   workloadSelector:
#     labels:
#       app: sleep
#   configPatches:
#     - applyTo: CLUSTER
#       match:
#         context: SIDECAR_OUTBOUND
#         routeConfiguration:
#           vhost:
#             name: "outbound|9080||reviews.load.svc.cluster.local"
#       patch:
#         operation: INSERT_FIRST
#         value:
#           # typed_config:
#           #   "@k": type.googleapis.com/envoy.extensions.filters.network.direct_response.v3.Config
#           #   response:
#           #     inline_string: NOT_FOUND
#           name: direct-response
#           match:
#             prefix: /reviews
#           directResponse:
#             body:
#               inlineString: '{"id": "101","podname": "reviews-v1-68b4dcbdb9-xwfsh","clustername": "null","reviews": [{  "reviewer": "Reviewer1",  "text": "Mock An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!"},{  "reviewer": "Reviewer2",  "text": "Mock Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare."}]}'
#           #   status: 200
---
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: reviews-lua
  namespace: load
spec:
  workloadSelector:
    labels:
      app: reviews
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_INBOUND
        routeConfiguration:
          portNumber: 9080
          vhost:
            name: "inbound|http|9080"
      patch:
        operation: INSERT_FIRST
        value:
          name: direct-response
          match:
            prefix: /reviews
          directResponse:
            body:
              inlineString: '{"id": "100","podname": "reviews-v1-68b4dcbdb9-xwfsh","clustername": "null","reviews": [{  "reviewer": "Reviewer1",  "text": "Mock An extremely entertaining play by Shakespeare. The slapstick humour is refreshing!"},{  "reviewer": "Reviewer2",  "text": "Mock Absolutely fun and entertaining. The play lacks thematic depth when compared to other plays by Shakespeare."}]}'
            status: 200
