name: Sync Postman

on:
  push:
    branches: [ main ]
    paths:
      - '**/collection.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Sync Postman Collections
        uses: jneate/postman-collection-action@v1
        with:
          postmanApiKey: ${{ secrets.postmanApiKey }}
          postmanWorkspaceId: 1f94fe93-e21e-4c77-9a43-cf2f96934003
          postmanTimeout: 30000
          
      - name: Commit Updated Postman Collection IDs
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.GH_USER_TOKEN }}
          branch: main
          unprotect_reviews: true
