{
 "title": "PRW output of k6",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "url", "query": { "query": "label_values(url)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   {
    "name": "interval",
    "query": "1s,5s,10s,20s,30s,1m,1m30s,2m,3m,4m,5m,10m,30m"
   },
   { "name": "method", "query": { "query": "label_values(method)" } }
  ]
 },
 "panels": [
  { "title": "Global metrics - VUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual Users (VUs)",
   "type": "table",
   "gridPos": { "h": 20, "w": 9, "x": 0, "y": 1 },
   "targets": [
    { "expr": "k6_vus{}" }
   ]
  },
  {
   "title": "Virtual users (VUs)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 9, "y": 1 },
   "targets": [
    { "expr": "k6_vus" }
   ]
  },
  {
   "title": "VUs / Max VUs",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 9, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "k6_vus", "legendFormat": "Actual VUs" },
    { "expr": "k6_vus_max", "legendFormat": "Max VUs possible" }
   ]
  },
  {
   "title": "Scenario level metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Data flow",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(k6_data_received{scenario=\"$scenario\"}[$interval])",
       "legendFormat": "Received"
      },
      {
       "expr": "rate(k6_data_sent{scenario=\"$scenario\"}[$interval])",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Iterations",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 12, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(k6_iterations{scenario=\"$scenario\"}[$interval])"
      }
     ]
    },
    {
     "title": "Avg iteration duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "k6_iteration_duration_avg{scenario=\"$scenario\"}"
      }
     ]
    },
    {
     "title": "Max iteration duration",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "k6_iteration_duration_max{scenario=\"$scenario\"}"
      }
     ]
    },
    {
     "title": "Iteration duration",
     "type": "graph",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "k6_iteration_duration_avg{scenario=\"$scenario\"}",
       "legendFormat": "avg"
      },
      {
       "expr": "k6_iteration_duration_max{scenario=\"$scenario\"}",
       "legendFormat": "max"
      },
      {
       "expr": "k6_iteration_duration_min{scenario=\"$scenario\"}",
       "legendFormat": "min"
      },
      {
       "expr": "k6_iteration_duration_med{scenario=\"$scenario\"}",
       "legendFormat": "median"
      },
      {
       "expr": "k6_iteration_duration_p90{scenario=\"$scenario\"}",
       "legendFormat": "90 percentile"
      },
      {
       "expr": "k6_iteration_duration_p95{scenario=\"$scenario\"}",
       "legendFormat": "95 percentile"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(rate(k6_http_reqs{url=~\"$url\",scenario=\"$scenario\"}[$interval]))",
       "legendFormat": "Total requests rate"
      }
     ]
    },
    {
     "title": "Failed requests rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_req_failed{url=~\"$url\",scenario=\"$scenario\"})",
       "legendFormat": "Failed requests"
      }
     ]
    },
    {
     "title": "Response time (avg)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_avg{url=~\"$url\",scenario=\"$scenario\",expected_response=\"true\"})",
       "legendFormat": "Successful responses"
      },
      {
       "expr": "avg(k6_http_req_duration_avg{url=~\"$url\",scenario=\"$scenario\",expected_response=\"false\"})",
       "legendFormat": "Failed responses"
      }
     ]
    },
    {
     "title": "Response time (95th)",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(k6_http_req_duration_p95{url=~\"$url\",scenario=\"$scenario\",expected_response=\"true\"})",
       "legendFormat": "Successful responses"
      },
      {
       "expr": "avg(k6_http_req_duration_p95{url=~\"$url\",scenario=\"$scenario\",expected_response=\"false\"})",
       "legendFormat": "Failed responses"
      }
     ]
    },
    {
     "title": "HTTP breakdown",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(k6_http_req_blocked_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
       "legendFormat": "Blocked"
      },
      {
       "expr": "sum(k6_http_req_waiting_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
       "legendFormat": "Waiting"
      },
      {
       "expr": "sum(k6_http_req_ending_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
       "legendFormat": "Sending"
      },
      {
       "expr": "sum(k6_http_req_receiving_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
       "legendFormat": "Receiving"
      },
      {
       "expr": "sum(k6_http_tls_handshaking_avg{url=~\"$url\",scenario=\"$scenario\",method=~\"$method\"})",
       "legendFormat": "TLS handshaking"
      }
     ]
    },
    {
     "title": "Requests by URL",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 37 },
     "targets": [
      {
       "expr": "count by (url) (k6_http_reqs{scenario=\"$scenario\",method=~\"$method\"})"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(k6_http_req_failed{url=~\"$url\",scenario=\"$scenario\",expected_response=\"false\"}) by (error)"
      }
     ]
    }
   ]
  },
  { "title": "default", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } }
 ]
}